language: cpp
dist: trusty
sudo: required
os:
  - linux

env:
  global:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmysqlclient-dev
      - doxygen
      - g++-4.9

script:
  - if [[ "${TRAVIS_EVENT_TYPE}" == "cron" && "${CXX}" == "g++-4.9"  ]];
    then ./.travis-ci.d/coverity_scan.sh;
    else ./.travis-ci.d/compile_and_test.sh;
    fi

before_install:
  - eval "${MATRIX_EVAL}"
  - ./.travis-ci.d/install_dependencies.sh

after_success:
  - ./.travis-ci.d/deploy-doxygen.sh

compiler:
  - gcc
  - clang

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
